### ISSUE TITLE
(XL) SC-5 Transfer Functionality

### ISSUE THREAD

**Issue by MuffinLightning** [peerplays-network/getscatter-walletpack#13]
### **User Story**

Add functionality such that Scatter wallet, when using the Peerplays plugin, will create a transfer transaction (with memo support) with inputs from the Scatter UI that will then be signed & broadcasted in another issue (#14).

### **Impacts**

Describe which portion(s) of Peerplays that may be impacted by your request. Please tick at least one box.

* [X] API (the application programming interface)
* [ ] Build (the build process or something prior to compiled code)
* [ ] Deployment (the deployment process after building such as Docker, Gitlab, etc.)
* [X] Performance (system or user efficiency, etc.)
* [ ] Protocol (the blockchain logic, consensus, validation, etc.)
* [ ] Security (the security of system or user data, etc.)
* [ ] UX (the User Experience)
* [ ] Other (please add below)

## Community / PBSA check list

* [x] Evaluate / Prioritize Feature Request
* [x] Refine User Stories / Requirements
* [x] Define Test Cases
* [x] Design / Develop Solution
* [ ] Perform QA/Testing
* [ ] Update Documentation

**Comment by mseaward** [comment]
Transaction building and fee setting based on transactions operations is now functional as of the merging of #29. However, we still need to check that the scatter UI will be compatible with the code from #29 before marking this issue as complete.

**Comment by mseaward** [comment]
Currently **blocked** due to incorrect transaction fee being returned by the blockchain method `get_required_fees` when a memo has been provided. Calculation of the fees under this circumstance is being researched by a backend developer.

More info:
When a transfer operation is broadcasted to the blockchain, we can optionally provide a memo (aes encrypted). When this is broadcasted, the blockchain will do some processing on the operation object it has received (to validate the info). This processing includes checking that the minimum fees required for the operation have been provided. The fees are calculated on the blockchain for a transfer operation that has a memo provided with the `calculate_data_fee` method which passes the byte size of the memo into it. The byte size of the memo is calculated with `fs::raw::pack_size`, what this exact calculation is and why it isn't always been made is being looked into.
We know that a transfer operation (with a memo) fees is supposed to be calculated by:
`fees = (memo_byte_size * price_per_kbyte) / 1024`
